name: Auto tests API

on:
  workflow_dispatch:
    inputs:
      deployment-target:
        description: 'Choose target'
        required: true
        default: 'test_api'
        type: choice
        options:
          - test_api
          - test_qa
          - another

jobs:
  tests:
    runs-on:
      ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Edge
        run: sudo apt-get install microsoft-edge-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: test_api
        if: "github.event.inputs.deployment_target == 'test_api' "
        run: pytest test_nnn_api\tests\test_Api.py
      - name: test_qa
        if: "github.event.inputs.deployment_target == 'test_qa' "
        run: pytest test_sixth_qa_practice\tests\test_simple_button.py, pytest test_sixth_qa_practice\tests\test_looks_like.py
      - name: another
        if: "github.event.inputs.deployment_target == 'another' "
        run: pytest pytests\test_forth_pytest.py